name: Playwright Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore WebApp.sln

      - name: Build solution
        run: '"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" WebApp.sln /p:Configuration=Debug'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
         node-version: '20'

      - name: Install Playwright dependencies
        run: npm install
        working-directory: PlaywrightTests

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: PlaywrightTests

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: PlaywrightTests