name: Playwright Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build solution with MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build solution
        run: |
          cd WebsiteGym.Web
          msbuild WebsiteGym.Web.sln /p:Configuration=Debug

      - name: Start the web app
        run: |
          cd WebsiteGym.Web
          start /B cmd /c "bin\Debug\WebsiteGym.Web.exe"
          timeout /t 10

      - name: Install Playwright and run tests
        run: |
          cd PlaywrightTests
          npm ci
          npx playwright install
          npx playwright test
