name: Run Playwright Tests on IIS Express

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    env:
      IIS_PATH: "C:\\Program Files (x86)\\IIS Express\\iisexpress.exe"
      WEB_PROJECT_PATH: "${{ github.workspace }}\\WebsiteGym.Web"
      TEMPLATE_CONFIG: "${{ github.workspace }}\\iisconfig\\applicationhost.config"
      ACTUAL_CONFIG: "${{ github.workspace }}\\iisconfig\\actual.config"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Replace site path in config
      run: |
        $template = Get-Content "$env:TEMPLATE_CONFIG"
        $template -replace 'C:\\site', "$env:WEB_PROJECT_PATH" | Set-Content "$env:ACTUAL_CONFIG"

    - name: Start IIS Express
      run: |
        Start-Process -FilePath "$env:IIS_PATH" `
                      -ArgumentList "/config:$env:ACTUAL_CONFIG", "/site:WebsiteGym.Web", "/apppool:Clr4IntegratedAppPool" `
                      -NoNewWindow

    - name: Wait for IIS to start
      run: |
        $retry = 0
        while ($retry -lt 15) {
          if (Test-NetConnection -ComputerName 'localhost' -Port 44336).TcpTestSucceeded) {
            Write-Host "✅ Port 44336 is open."
            break
          }
          Write-Host "⏳ Port not open yet, retrying... attempt $($retry + 1) of 15"
          Start-Sleep -Seconds 2
          $retry++
        }
        if ($retry -eq 15) {
          throw "❌ Port 44336 is NOT open after 15 attempts"
        }

    - name: Install dependencies
      run: npm ci
      working-directory: PlaywrightTests

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: PlaywrightTests

    - name: Kill IIS Express
      if: always()
      shell: pwsh
      run: |
        Get-Process iisexpress -ErrorAction SilentlyContinue | Stop-Process -Force