name: CI - Build & E2E Tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: nuget restore WebApp.sln

      - name: Build Solution with MSBuild
        shell: pwsh
        run: msbuild WebApp.sln /p:Configuration=Debug

      - name: Install Playwright dependencies
        run: npm install
        working-directory: PlaywrightTests

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: PlaywrightTests

      - name: Start IIS Express
        shell: pwsh
        run: |
          $iisPath = "${env:ProgramFiles(x86)}\IIS Express\iisexpress.exe"
          Start-Process $iisPath -ArgumentList '/path:"WebsiteGym.Web"', '/port:44336' -NoNewWindow
          Start-Sleep -Seconds 10

      - name: Run Playwright tests
        run: npx playwright test --project=chromium
        working-directory: PlaywrightTests

      - name: Check IISExpress logs (optional debug)
        shell: pwsh
        run: |
          Get-Content "$env:USERPROFILE\Documents\IISExpress\logs\trace.log" -ErrorAction SilentlyContinue
