name: Run Playwright Tests on IIS Express

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup IIS Express path
      shell: pwsh
      run: |
        $iisPath = "${env:ProgramFiles(x86)}\IIS Express\iisexpress.exe"
        Write-Output "IIS Express path: $iisPath"

    - name: Start IIS Express
      shell: pwsh
      run: |
        $webProjectPath = "$env:GITHUB_WORKSPACE\WebsiteGym.Web"
        $iisPath = "${env:ProgramFiles(x86)}\IIS Express\iisexpress.exe"
        
        # Pornim IIS Express direct pe folderul proiectului, port 44336
        $arguments = "/path:`"$webProjectPath`" /port:44336"
        Write-Output "Starting IIS Express with args: $arguments"
        
        Start-Process -FilePath $iisPath -ArgumentList $arguments -NoNewWindow
        
        # Așteptăm să se pornească
        Start-Sleep -Seconds 10

    - name: Check if IIS Express port is open
      shell: pwsh
      run: |
        $port = 44336
        $maxAttempts = 15
        $attempt = 0
        $open = $false

        while ($attempt -lt $maxAttempts -and -not $open) {
          try {
            $tcpClient = New-Object System.Net.Sockets.TcpClient("localhost", $port)
            $open = $true
            $tcpClient.Close()
          } catch {
            Write-Output "Port $port not open yet, retrying... attempt $($attempt + 1) of $maxAttempts"
            Start-Sleep -Seconds 2
          }
          $attempt++
        }

        if (-not $open) {
          Write-Error "Port $port is NOT open after $maxAttempts attempts"
          exit 1
        } else {
          Write-Output "Port $port is open."
        }

    - name: Install dependencies
      run: npm ci
      working-directory: PlaywrightTests

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: PlaywrightTests

    - name: Kill IIS Express
      if: always()
      shell: pwsh
      run: |
        Get-Process iisexpress -ErrorAction SilentlyContinue | Stop-Process -Force