name: Playwright Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # ajustează după cum ai nevoie

      - name: Restore dependencies
        run: dotnet restore WebApp.sln

      - name: Build solution
        run: dotnet build WebApp.sln --no-restore --configuration Debug

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright dependencies
        run: npm install
        working-directory: PlaywrightTests

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: PlaywrightTests

      - name: Run web app
        run: dotnet run --no-build --project WebsiteGym.Web/WebsiteGym.Web.csproj --urls "https://localhost:5001"
        shell: pwsh
        env:
          ASPNETCORE_ENVIRONMENT: Development
        # Rulează în background
        continue-on-error: true

      - name: Wait for the app to be ready
        run: |
          $retries = 0
          do {
            Start-Sleep -Seconds 2
            $response = try { Invoke-WebRequest -Uri https://localhost:5001 -UseBasicParsing -SkipCertificateCheck } catch { $null }
            $retries++
          } while (!$response -and $retries -lt 15)
          if (!$response) { throw "App did not start in time" }
        shell: pwsh

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: PlaywrightTests
        env:
          BASE_URL: https://localhost:5001
