name: CI - Build & E2E Tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore WebApp.sln

      - name: Build Solution with MSBuild
        run: msbuild WebApp.sln /p:Configuration=Debug /t:Rebuild

      - name: Install Playwright dependencies
        run: npm install
        working-directory: PlaywrightTests

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: PlaywrightTests

      - name: Start IIS Express
        shell: pwsh
        run: |
          $iisPath = "${env:ProgramFiles(x86)}\IIS Express\iisexpress.exe"
          $sitePath = Resolve-Path "$env:GITHUB_WORKSPACE\WebsiteGym.Web"
          Start-Process $iisPath -ArgumentList "/path:`"$sitePath`"", '/port:44336', '/clr:4.0' -NoNewWindow
          Start-Sleep -Seconds 10

      - name: Check IIS site is up
        shell: pwsh
        run: curl -v http://localhost:44336

      - name: Run Playwright tests
        run: npx playwright test --project=chromium --reporter=html
        working-directory: PlaywrightTests

      - name: Upload Playwright report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: PlaywrightTests/playwright-report
