name: ASP.NET & Playwright Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: nuget restore WebApp.sln

      - name: Build solution
        run: msbuild WebApp.sln /p:Configuration=Debug

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright dependencies
        run: npm install
        working-directory: PlaywrightTests

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: PlaywrightTests

      - name: Start IIS Express
        run: |
          Start-Process -FilePath "C:\Program Files\IIS Express\iisexpress.exe" `
            -ArgumentList '/path:"D:\a\gym-website\gym-website\WebsiteGym.Web"', '/port:44336' `
            -NoNewWindow
        shell: pwsh

      - name: Wait for app to start
        run: Start-Sleep -Seconds 10
        shell: pwsh

      - name: Check IISExpress logs
        run: Get-Content "$env:USERPROFILE\Documents\IISExpress\logs\trace.log" -ErrorAction SilentlyContinue
        shell: pwsh

      - name: Check if app is running
        run: curl -k https://localhost:44336
        shell: pwsh

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: PlaywrightTests
        shell: pwsh