name: Build and Run ASP.NET Website

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore WebApp.sln

      - name: Build solution with MSBuild
        run: msbuild WebApp.sln /p:Configuration=Debug /t:Rebuild
        env:
          VSToolsPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0'

      - name: Start IIS Express
        run: |
          Start-Process "C:\Program Files\IIS Express\iisexpress.exe" `
            -ArgumentList '/path:"WebsiteGym.Web"', '/port:44336' `
            -NoNewWindow
        shell: pwsh

      - name: Wait for website to start
        run: |
          for ($i = 0; $i -lt 10; $i++) {
            try {
              $response = Invoke-WebRequest -Uri https://localhost:44336 -UseBasicParsing -SkipCertificateCheck
              if ($response.StatusCode -eq 200) { break }
            } catch {}
            Start-Sleep -Seconds 3
          }

      - name: Run tests (Playwright or other)
        run: |
          npm ci
          npx playwright install
          npx playwright test
